development:
  charset_table: "0..9, A..Z->a..z, _, a..z"
production:
  charset_table: "0..9, A..Z->a..z, _, a..z"
  pid_file: /srv/rails/abtt/shared/pids/searchd.pid
  indices_location: /srv/rails/abtt/shared/sphinx
  configuration_file: /srv/rails/abtt/shared/config/production.sphinx.conf
  binlog_path: /srv/rails/abtt/shared/binlog